TehnologiiWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = "main"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('post/', include('posts.urls')),
    path('group/', include('groups.urls')),
    path('search/', include('search.urls')),
    path('project/', include('projects.urls')),
    path('', views.homepage, name="homepage"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('<username>/', views.user_view, name="user_account"),
    path('login', views.login_view, name="login"),
    path('signup', views.register_view, name="signup"),
    path('logout', views.logout_view, name="logout"),
    path('<username>/change_user/', views.change_user, name="change_user"),
    path('<username>/liked_posts/', views.liked_posts, name="liked_posts"),
    path('add_friend/<user_to_username>', views.add_friend, name="add_friend"),
    path('remove_friend/<user_to_username>', views.remove_friend, name="remove_friend"),
    path('accept_friend/<request_id>', views.accept_friend, name="accept_friend_request"),
    path('decline_friend/<request_id>', views.decline_friend, name="decline_friend_request")
]

groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('create-group/', views.create_group, name="create_group"),
    path('<group_name>', views.group_page, name="group_page"),
    path('<group_name>/enter_group/', views.enter_group, name="enter_group"),
    path('<group_name>/leave_group/', views.leave_group, name="leave_group"),
    path('<group_name>/delete_group/', views.delete_group, name="delete_group"),
    path('<group_name>/change_group_data/', views.change_group, name="change_group"),
    path('<group_name>/members/', views.group_members, name="group_members"),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('<slug>', views.post_page, name="post_details"),
    path('create_post/', views.create_post, name="create_post"),
    path('comment/', views.post_comment, name="post_comment"),
    path('like/', views.like_post, name="like_post"),
    path('send_message/', views.send_message, name="send_message"),
    path('get_messages/', views.get_messages, name="get_messages"),
]

groups/models.py
from django.db import models
from django.contrib.auth.models import Group, User
from django.db.models.signals import post_save
from django.dispatch import receiver


def is_member(user, group):
    return user.groups.filter(name=group.name).exists()


def is_admin(user, group):
    return group.user_set.filter(id=user.id).exists()


class GroupProfile(models.Model):
    name = models.TextField(default="Feed")
    group = models.OneToOneField(Group, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    avatar = models.ImageField(default='avatar-default.png', blank=True)
    is_feed = models.BooleanField(default=False)
    description = models.TextField()


@receiver(post_save, sender=Group)
def create_group_profile(sender, instance, created, **kwargs):
    if created:
        GroupProfile.objects.create(group=instance)
        instance.groupprofile.name = instance.name
        instance.save()


@receiver(post_save, sender=Group)
def save_group_profile(sender, instance, **kwargs):
    instance.groupprofile.save()

groups/forms.py
from django import forms
from django.contrib.auth.models import Group


class CreateGroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']


class ChangeGroupForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea)
    media = forms.ImageField()

    class Meta:
        model = Group
        fields = ['name']

groups/views.py
from django.contrib.auth.models import Group, User
from django.shortcuts import render, redirect
from PIL import Image

from posts.models import Post
from .models import is_member as member
from .models import is_admin as admin
from .forms import CreateGroupForm, ChangeGroupForm


def create_group(request):
    if request.method == 'POST':
        create_form = CreateGroupForm(request.POST)
        if create_form.is_valid():
            group = create_form.save()
            group.groupprofile.name = group.name
            group.user_set.add(request.user)
            group.groupprofile.owner = request.user
            group.save()
            return redirect('accounts:user_account', username=request.user.username)
    else:
        create_form = CreateGroupForm()
    return render(request, 'groups/create_group.html', {'create_form': create_form})


def resize_img(pimg):
    img = Image.open(pimg.path)
    if img.height > img.width:
        left = 0
        right = img.width
        top = (img.height - img.width) / 2
        bottom = (img.height + img.width) / 2
        img = img.crop((left, top, right, bottom))
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(pimg.path)

    elif img.width > img.height:
        left = (img.width - img.height) / 2
        right = (img.width + img.height) / 2
        top = 0
        bottom = img.height
        img = img.crop((left, top, right, bottom))
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(pimg.path)


def group_page(request, group_name):
    group = Group.objects.get(name=group_name)
    user = User.objects.get(username=request.user.username)
    is_member = member(user, group)
    is_admin = admin(user, group)
    posts = Post.objects.filter(host_group=group).order_by('-date')
    change_form = ChangeGroupForm(initial={
        'name': group.name,
        'description': group.groupprofile.description,
        'media': group.groupprofile.avatar
    })
    return render(request, 'groups/group_page.html', {'group': group,
                                                      'posts': posts,
                                                      'is_member': is_member,
                                                      'is_admin': is_admin,
                                                      'change_form': change_form,
                                                      })


def enter_group(request, group_name):
    group = Group.objects.get(name=group_name)
    group.user_set.add(User.objects.get(username=request.user.username))
    return redirect('groups:group_page', group_name=group_name)


def leave_group(request, group_name):
    group = Group.objects.get(name=group_name)
    group.user_set.remove(User.objects.get(username=request.user.username))
    return redirect('groups:group_page', group_name=group_name)


def change_group(request, group_name):
    if request.method == 'POST':
        group = Group.objects.get(name=group_name)
        change_form = ChangeGroupForm(request.POST, request.FILES)
        name = group_name
        da = group.name == request.POST["name"]
        if da:
            description = change_form.data.get('description')
            group.groupprofile.description = description
            if len(request.FILES) != 0:
                group.groupprofile.avatar = request.FILES["media"]
            group.save()
        else:
            if change_form.is_valid():
                name = change_form.cleaned_data.get('name')
                description = change_form.cleaned_data.get('description')
                group.name = name
                group.groupprofile.name = name
                group.groupprofile.description = description
                if len(request.FILES) != 0:
                    group.groupprofile.avatar = request.FILES["media"]
                group.save()
        resize_img(group.groupprofile.avatar)
    return redirect('groups:group_page', group_name=name)


def delete_group(request, group_name):
    group = Group.objects.get(name=group_name)
    group.delete()
    return redirect('homepage')


def group_members(request, group_name):
    group = Group.objects.get(name=group_name)
    user = User.objects.get(username=request.user.username)
    is_member = member(user, group)
    is_admin = admin(user, group)
    members = group.user_set.all()
    change_form = ChangeGroupForm(initial={
        'name': group.name,
        'description': group.groupprofile.description,
        'media': group.groupprofile.avatar
    })
    return render(request, 'groups/group_members.html', {'group': group,
                                                         'is_member': is_member,
                                                         'members': members,
                                                         'is_admin': is_admin,
                                                         'change_form': change_form,
                                                         })

groups/templates/groups/create_group.html
{% extends 'base_layout.html' %}

    {% block title %}
        <title>
            Create group
        </title>
    {% endblock %}

    {% block content %}
        <form class = "site-form" action = "{% url 'groups:create_group' %}" method="post">
            {% csrf_token %}
            {{ create_form }}
            <input type = "submit" value = "Create">
        </form>
    {% endblock %}

groups/templates/groups/group_members.html
{% extends 'base_layout.html' %}
{% load tz %}

{% block title %}
    {{ group.name }} | CodeRu
{% endblock %}

{% block content %}
    <div class="row content">
        <div class="col-sm-12" style="background-color: #3e3e42; margin-top: 15px;margin-left: 15px; border-radius: 4px; overflow: auto; max-height: 910px">
            <div style="border-radius: 4px; overflow-y: auto; word-break: normal;" class="col-sm-12">
                <div class="container text-center">
                    <div class="row content" style="align-items: center">
                        <div style="border-radius: 4px; margin-top:50px;" class="col-sm-2 sidenav">
                            <img id = "{{ group.name }}" src="{{ group.groupprofile.avatar.url }}" height="200px" style="border-radius: 50%">
                            <div id="{{ group.name }}myModal" class="imgModal">
                                <span id = "{{ group.name }}close" class="imgClose">&times;</span>
                                <img style = "border-radius: 4px; max-height: 600px; max-width: 600px" class="imgModal-content" id="{{ group.name }}img01">
                            </div>
                            <script>
                                $("#{{ group.name }}").click(function () {
                                    const modal = document.getElementById("{{ group.name }}myModal");

                                    const img = document.getElementById("{{ group.name }}");
                                    const modalImg = document.getElementById("{{ group.name }}img01");
                                    img.onclick = function(){
                                        modal.style.display = "block";
                                        modalImg.src = this.src;
                                    }

                                    const span = document.getElementById("{{ group.name }}close");

                                    span.onclick = function() {
                                        modal.style.display = "none";
                                    }
                                })
                            </script>
                        </div>
                        <div style="border-radius: 4px; margin-top:50px; height:210px; padding: 60px 0; word-break: normal;" class="col-sm-10 sidenav">
                            <h1 style="color: darkgray">{{ group.name }}</h1>
                            <p style="color: darkgray">{{ group.groupprofile.description }}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% if is_admin %}
                <div class="modal fade" id="changeGroupModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLongTitle">Change group info</h5>
                            </div>
                            <div class="modal-body">
                                <form class="site-form" method="post" action="{% url 'groups:change_group' group_name=group.name %}" id="change-group-form" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ change_form }}
                                </form>
                                <form class="site-form" action="{% url 'groups:delete_group' group_name=group.name %}" method="post" id="delete-group-form">
                                    {% csrf_token %}
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-light" data-mdb-ripple-color="dark" form="change-group-form">Change group</button>
                                <button type="submit" class="btn btn-light" data-mdb-ripple-color="dark" form="delete-group-form">Delete group</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
            <hr style="color: white">
            <form class = "site-form d-flex" method = "post" action = "{% url 'groups:enter_group' group_name=group.name %}" id = "enter-group">
                {% csrf_token %}
                {% if is_member %}
                    <button type = "submit" class="btn btn-light" data-mdb-ripple-color="dark" form = "leave-group">Leave group</button>
                    <button style="margin-left: 5px" type="submit" class="btn btn-light" data-mdb-ripple-color="dark" form="group-members">Group members</button>
                {% else %}
                    <button type = "submit" class="btn btn-light" data-mdb-ripple-color="dark" form = "enter-group">Enter group</button>
                {% endif %}
                {% if is_admin %}
                    <button style="margin-left: 5px" type = "button" class="btn btn-light" data-mdb-ripple-color="dark" data-bs-toggle="modal" data-bs-target="#changeGroupModal">Change</button>
                {% endif %}
            </form>

            <ul class="list-group shadow">
                {% for user in members %}
                    <a href="{% url 'accounts:user_account' username=user.username %}">
                        <li class="list-group-item bg-blackk"">
                            <div class="row" style="max-height: 200px">
                                <div class="col-md-1">
                                    <img src="{{ user.profile.avatar.url }}" style="width: 100px; height: 100%; border-radius: 50%">
                                </div>
                                <div class="col-md-10 justify-content-center">
                                    <h1 class="mt-0 font-weight-bold mb-2" style="color: gray">
                                        {{ user.get_full_name }}
                                    </h1>
                                    <h3 class="mt-0 font-weight-bold mb-2 text-muted" style="color: gray">
                                        {{ user.groups.all.0.user_set.count }} friends
                                    </h3>
                                </div>
                            </div>
                        </li>
                    </a>
                {% endfor %}
            </ul>

        </div>

        <form class = "site-form d-flex" method = "post" action = "{% url 'groups:leave_group' group_name=group.name %}" id = "leave-group">
            {% csrf_token %}
        </form>
        <form class = "site-form d-flex" method = "post" action = "{% url 'groups:group_members' group_name=group.name %}" id = "group-members">
            {% csrf_token %}
        </form>
    </div>
{% endblock %}